// <auto-generated />
using System;
using FoundersPC.Infrastructure.Identity.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

namespace FoundersPC.Infrastructure.Identity.Migrations
{
	[DbContext(typeof(FoundersPCDbIdentityUsersContext))]
	internal class FoundersPCDbIdentityUsersContextModelSnapshot : ModelSnapshot
	{
		protected override void BuildModel(ModelBuilder modelBuilder)
		{
			#pragma warning disable 612, 618
			modelBuilder
					.HasAnnotation("Relational:MaxIdentifierLength", 128)
					.HasAnnotation("ProductVersion", "5.0.3")
					.HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

			modelBuilder.Entity("FoundersPC.Domain.Entities.Users.Role",
								b =>
								{
									b.Property<int>("Id")
									 .ValueGeneratedOnAdd()
									 .HasColumnType("int")
									 .HasColumnName("Id")
									 .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

									b.Property<string>("RoleTitle")
									 .IsRequired()
									 .HasColumnType("nvarchar(max)");

									b.HasKey("Id");

									b.HasIndex("Id");

									b.ToTable("Roles");
								});

			modelBuilder.Entity("FoundersPC.Domain.Entities.Users.User",
								b =>
								{
									b.Property<int>("Id")
									 .ValueGeneratedOnAdd()
									 .HasColumnType("int")
									 .HasColumnName("Id")
									 .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

									b.Property<DateTime>("CreatedAt")
									 .HasColumnType("datetime2");

									b.Property<string>("Email")
									 .IsRequired()
									 .HasColumnType("nvarchar(max)");

									b.Property<bool>("IsActive")
									 .HasColumnType("bit");

									b.Property<bool>("IsEmailConfirmed")
									 .HasColumnType("bit");

									b.Property<string>("Login")
									 .HasMaxLength(20)
									 .HasColumnType("nvarchar(20)");

									b.Property<string>("PasswordHash")
									 .IsRequired()
									 .HasColumnType("nvarchar(max)");

									b.Property<int>("RoleId")
									 .HasColumnType("int");

									b.HasKey("Id");

									b.HasIndex("Id");

									b.HasIndex("RoleId");

									b.ToTable("Users");
								});

			modelBuilder.Entity("FoundersPC.Domain.Entities.Users.User",
								b =>
								{
									b.HasOne("FoundersPC.Domain.Entities.Users.Role", "Role")
									 .WithMany()
									 .HasForeignKey("RoleId")
									 .OnDelete(DeleteBehavior.Cascade)
									 .IsRequired();

									b.Navigation("Role");
								});
			#pragma warning restore 612, 618
		}
	}
}